// Authentication Actions
export const authenticationAction = {
    USER_LOGIN_INITIATE: "USER_LOGIN_INITIATE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    USER_LOGOUT: 'USER_LOGOUT',

    API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",

    DRAWER_EVENT:"DRAWER_EVENT",

    CLEAR_USER_DATA: "CLEAR_USER_DATA",
};